version: "2"
checks:
  similar-code:
    enabled: false
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - "tests/"
  - "spec/"
  - "**/*.spec.js"
  - "**/*.spec.jsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/vendor/"
  - "**/node_modules/"
